FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY mvc1.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o /app/dist

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/dist .
EXPOSE 8080
CMD ["dotnet", "mvc1.dll"]